# Generated by Django 5.0.1 on 2024-01-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='med_school_year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Sixth Year'), (6, 'Seventh Year')]),
        ),
    ]
