# Generated by Django 5.0.1 on 2024-01-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_alter_question_med_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='letter',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
